services:
  agent:
    image: baykara/jenkins-swarm-agent:v0.1.1
    command: java -jar swarm-client-3.44.jar -name ${NODE_NAME} -master ${JENKINS_URL} -username ${SWARM_USER} -password ${SWARM_PASS} -executors ${SWARM_EXECUTORS} -labels ${LABELS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.m2:/root/.m2
    restart: on-failure
    env_file:
      - "./.env"
