spring:
  version: v3
  application:
    name: spring-cloud-app

management:
    endpoints:
        web:
            exposure:
                include: '*'
  
    endpoint:
      restart:
        enabled: true