management:
  endpoint:
    web:
      exposure:
        inculde: info, refresh, keepalive, health
spring:
  application:
    name: spring-cloud
  profiles:
    active: development
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    root: INFO