spring:
  application:
    name: ${APP_NAME:application}
  cloud:
    kubernetes:
      enabled: ${K8S_MODE:false}
      config:
        sources:
          - namespace: ${NAMESPACE:default}
            name: ${spring.application.name}
management:
  endpoint:
      enabled: true  
  endpoints:
    web:
      exposure:
        include: "refresh"
