apiVersion: v1
kind: ConfigMap
metadata:
  name:  spring-cloud-app
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    name: myapp
    spring:
      version: v3
      application:
        name: foo