apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud
spec:
  selector:
      matchLabels:
        app: spring-cloud
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud
    spec:
      serviceAccountName:  spring-cloud-acc
      containers:
        - name: spring-cloud
          image: baykara/springcloud
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
