---
apiVersion: v1
kind: Service
metadata:
  labels:
     run: spring-cloud
  name: spring-cloud
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
     run: spring-cloud
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud
spec:
  selector:
      matchLabels:
        app: spring-cloud
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud
    spec:
      serviceAccountName:  spring-cloud-acc
      containers:
        - name: spring-cloud
          image: baykara/springcloud
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
