apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-app
spec:
  selector:
      matchLabels:
        app: spring-cloud-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-app
    spec:
      volumes:
      - name: config
        configMap:
          name: spring-cloud-app
      serviceAccountName:  spring-cloud-acc
      containers:
        - name: spring-cloud
          image: baykara/springcloud
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
--- 
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-app
  labels:
    app: spring-cloud-app
spec:
  selector:
    app: spring-cloud-app
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080