kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "secrets","endpoints"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud-rb
subjects:
  - kind: ServiceAccount
    name:  spring-cloud-acc
    apiGroup: ""
roleRef:
  kind: Role
  name:  spring-cloud-role
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: spring-cloud-acc
 
